library("tidyverse")
library("scRepertoire")
library("Seurat")
library("SeuratDisk")
library("patchwork")
library("khroma")
library("org.Hs.eg.db")
library("pheatmap")
library("viridis")

sink("log/library_versions.txt")
sessionInfo()
sink()