library("utils")

# Package list generated by local grateful report

library("argparse")
library("base")
library("circlize")
library("ComplexHeatmap")
library("hdf5r")
library("janitor")
library("Matrix")
library("patchwork")
library("rhdf5")
library("scales")
library("scRepertoire")
library("Seurat")
library("SeuratDisk")
library("tidyverse")


writeLines(capture.output(sessionInfo()), "sessionInfo.txt")

# package_version

x <- paste0("We used R version 4.4.2 (R Core Team 2024) and the following R ",
            "packages: argparse v. %s (Davis 2024), circlize v. %s",
            "(Gu et al. 2014), ComplexHeatmap v. %s ",
            "(Gu, Eils, and Schlesner 2016; Gu 2022), ggrepel v. %s ",
            "(Slowikowski 2024), hdf5r v. %s (Hoefling and Annau 2025),",
            " janitor v. %s (Firke 2024), Matrix v. %s ",
            "(Bates, Maechler, and Jagan 2025), patchwork v. %s (Pedersen 2024),",
            "rhdf5 v. %s (Fischer, Smith, and Pau 2024), scales v. %s",
            "(Wickham, Pedersen, and Seidel 2023), scRepertoire v. %s ",
            "(Borcherding, Bormann, and Kraus 2022), Seurat v. %s ",
            "(Satija et al. 2015; Butler et al. 2018; Stuart et al. 2019; ",
            "Hao et al. 2021, 2023), SeuratDisk v. %s (Hoffman 2023),",
            "tidyverse v. %s (Wickham et al. 2019).")